[general]
import = [
    "theme.toml"
]
live_config_reload = true

[window]
decorations = "none"

[window.padding]
x = 1
y = 0

[font]
normal = { family = "NotoMono", style = "Regular" }
bold = { family = "NotoMono", style = "Bold" }
italic = { family = "NotoMono", style = "Italic" }
size = 12.0

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

