[general]
import = [
    "theme.toml"
]
live_config_reload = true

[window]
padding = { x = 4, y = 4 }
decorations = "none"

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "Noto Mono", style = "Regular" }
#bold = { family = "Noto Mono", style = "Bold" }
#italic = { family = "Noto Mono", style = "Italic" }
size = 14.0

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true

