[window]
decorations_theme_variant = "Dark"

[colors]
cursor = { text = "#121212", cursor = "#ffffff" }
vi_mode_cursor = { text = "#121212", cursor = "#ffffff" }

selection = { foreground = "#121212", background = "#8af4f8" }

[colors.primary]
foreground = "#ffffff"
background = "#121212"

[colors.normal]
black = "#121212"
red = "#d50000"
green = "#6d9f26"
yellow = "#ce7226"
blue = "#4d1ef5"
magenta = "#8f00f5"
cyan = "#4ddef5"
white = "#c0c0c0"

[colors.bright]
black = "#636363"
red = "#e3593c"
green = "#9fdf61"
yellow = "#dfd061"
blue = "#8ab4f8"
magenta = "#b58af8"
cyan = "#8af4f8"
white = "#ffffff"

